import { ai } from '../genkit';
import { z } from 'genkit';

const GenerateArrayFoodFromPromptInputSchema = z.object({
    prompt: z.string().describe('The prompt to use for generating the food array.'),
});
export type GenerateArrayFoodFromPromptInput = z.infer<typeof GenerateArrayFoodFromPromptInputSchema>;

const GenerateArrayFoodFromPromptOutputSchema = z.object({
    foods: z.array(z.string().describe('A food item generated from the prompt.'))
        .describe('The list of foods generated by the model.'),
});
export type GenerateArrayFoodFromPromptOutput = z.infer<typeof GenerateArrayFoodFromPromptOutputSchema>;

export async function generateArrayFoodFromPrompt(
    input: GenerateArrayFoodFromPromptInput
): Promise<GenerateArrayFoodFromPromptOutput> {
    return generateArrayFoodFromPromptFlow(input);
}

const generateArrayFoodFromPromptPrompt = ai.definePrompt({
    name: 'generateArrayFoodFromPromptPrompt',
    input: { schema: GenerateArrayFoodFromPromptInputSchema },
    output: { schema: GenerateArrayFoodFromPromptOutputSchema },
    prompt: `
Bạn là một chuyên gia dinh dưỡng và ẩm thực Việt Nam. 
Hãy phân tích yêu cầu của người dùng và đưa ra danh sách các món ăn phù hợp.

YÊU CẦU NGƯỜI DÙNG: "{{{prompt}}}"

Hãy trả về một chuỗi mô tả ngắn gọn các loại món ăn, tính chất, nguyên liệu, hoặc đặc điểm dinh dưỡng phù hợp với yêu cầu này, ưu tiên sử dụng ví dụ có sẵn. 
⚠️ Lưu ý:
- Chú ý thời tiết của người dùng để gợi ý món ăn phù hợp
- Chỉ trả về danh sách món ăn/nhóm thực phẩm/nguyên liệu ngắn gọn, cách nhau bằng dấu phẩy.
- Không giải thích, không mở ngoặc.
- Tập trung vào món ăn Việt Nam và một số món quốc tế phổ biến.
- Giới hạn chỉ cần gợi ý 5 món
- Đảm bảo đồng bộ theo ví dụ sau:

VÍ DỤ:
- "tôi bị bệnh" → "cháo, phở, súp, canh nhẹ, thức ăn mềm, dễ tiêu hóa, ít gia vị"
- "muốn giảm cân" → "salad, rau xanh, protein ít béo, gà luộc, cá nướng, calories thấp"
- "món ăn vặt" → "bánh tráng, chè, bánh flan, nem chua, bánh căn, snack"
- "nhạt miệng" → "món mặn, kho, rim"
- "buồn" → "chè, bánh, socola, sữa nóng"
- "vui" → "BBQ, lẩu, pizza, gỏi cuốn, trà sữa, kem"

Kết quả trả về theo cấu trúc:
{
  "foods": ["Phở", "Bánh mì", "Cơm tấm"]
}
  `,
});

const generateArrayFoodFromPromptFlow = ai.defineFlow(
    {
        name: 'generateArrayFoodFromPromptFlow',
        inputSchema: GenerateArrayFoodFromPromptInputSchema,
        outputSchema: GenerateArrayFoodFromPromptOutputSchema,
    },
    async input => {
        const { output } = await generateArrayFoodFromPromptPrompt(input);
        return output!;
    }
);
